// Precompile blog MDX files into plain React components at build time.
//
// Why: the app renders MDX via `new Function(code)` (see
// src/components/Blog/MdxContent.js). Cloudflare Workers forbids
// dynamic code generation, so post bodies could not render there.
// Compiling to static modules here (Node, at build time) removes all runtime eval.
//
// Mirrors the velite MDX pipeline (velite.config.js) so output matches.
//
// Usage: node scripts/compile-mdx.mjs
// Output: src/content/compiled/<slug>.jsx + src/content/compiled/index.js
import { readdir, readFile, writeFile, mkdir } from "node:fs/promises"
import path from "node:path"
import { fileURLToPath } from "node:url"
import { compile } from "@mdx-js/mdx"
import remarkGfm from "remark-gfm"
import rehypeSlug from "rehype-slug"
import rehypePrettyCode from "rehype-pretty-code"
import rehypeAutolinkHeadings from "rehype-autolink-headings"

const root = path.dirname(fileURLToPath(import.meta.url))
const blogDir = path.join(root, "..", "content", "blogs")
const outDir = path.join(root, "..", "src", "content", "compiled")

async function* walk(dir) {
	for (const entry of await readdir(dir, { withFileTypes: true })) {
		const full = path.join(dir, entry.name)
		if (entry.isDirectory()) yield* walk(full)
		else if (entry.name.endsWith(".mdx")) yield full
	}
}

const files = []
for await (const f of walk(blogDir)) files.push(f)
if (files.length === 0) {
	console.log("No MDX files found, nothing to compile.")
	process.exit(0)
}

const codeOptions = {
	theme: 'github-dark',
	grid: false,
}

const entries = []
for (const file of files) {
	// slug is the directory name under content/blogs
	const rel = path.relative(blogDir, path.dirname(file))
	// Read raw MDX, strip frontmatter (velite handles it, we just need the body)
	const raw = await readFile(file, "utf8")
	const content = raw.replace(/^---\n[\s\S]*?\n---\n/, "")

	const compiled = await compile(content, {
		outputFormat: "program",
		development: false,
		remarkPlugins: [remarkGfm],
		rehypePlugins: [
			rehypeSlug,
			[rehypeAutolinkHeadings, { behavior: "append" }],
			[rehypePrettyCode, codeOptions],
		],
	})

	const outFile = path.join(outDir, `${rel}.jsx`)
	await mkdir(path.dirname(outFile), { recursive: true })
	await writeFile(outFile, String(compiled))

	const varName = "Post_" + rel.replace(/[^a-zA-Z0-9]/g, "_")
	const importPath = `./${rel}.jsx`
	entries.push({ slug: rel, varName, importPath })
	console.log(`compiled ${rel}`)
}

const index = `// GENERATED by scripts/compile-mdx.mjs — do not edit by hand.
${entries.map((e) => `import ${e.varName} from "${e.importPath}"`).join("\n")}

export const mdxComponents = {
${entries.map((e) => `  "${e.slug}": ${e.varName},`).join("\n")}
}
`
await writeFile(path.join(outDir, "index.js"), index)
console.log(`wrote index.js with ${entries.length} posts`)
